<?php 
/**
 * Webkul DailyDeals Product Edit
 *
 * @category  Webkul
 * @package   Webkul_DailyDeals
 * @author    Webkul
 * @copyright Copyright (c) 2010-2016 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */


$dealsDateTime = $block->getDealsDateTime();
if ($dealsDateTime) { ?>
	<script type="text/x-magento-init">
	    {
	        "*": {
	            "Webkul_MpDailyDeal/js/setattribute": {
	            		"dealFrom": "<?php /* @noEscape */ echo $dealsDateTime['deal_from_date'] ?>",
	            		"dealTo": "<?php /* @noEscape */ echo $dealsDateTime['deal_to_date'] ?>",
	            		"dateFormat" :"<?php /* @noEscape */ echo $dealsDateTime['date_format'] ?>"
	            }
	        }
	    }
	</script>
<?php } ?>

