<!--
/**
 * Webkul_MpDailyDeal Navigation.
 * @category  Webkul
 * @package   Webkul_MpDailyDeal
 * @author    Webkul
 * @copyright Copyright (c) 2010-2016 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
-->
<?php 
$helper = $this->helper('Webkul\Marketplace\Helper\Data');
if ($helper->isSeller()){ ?>
	<li class="mp-daily-deal nav item <?php /* @escapeNotVerified */ echo $block->getCurrentNavClass('mpdailydeal/account')?>">  
		<?php if($block->getCurrentNavClass('mpdailydeal/account')){ ?>   
		    <strong><?php /* @escapeNotVerified */ echo __('Daily Deal') ?></strong>        
		<?php 
		} else { ?>    
		    <a href="#"><?php /* @escapeNotVerified */ echo __('Daily Deal') ?></a>                
		<?php } ?>
		<ul class="nav items">
			<li class="nav item <?php /* @escapeNotVerified */ echo $block->getCurrentNavClass('mpdailydeal/account/index');?>">
				<?php if ($block->getCurrentNavClass('mpdailydeal/account/index')) { ?>   
				    <strong><?php /* @escapeNotVerified */ echo __('Add Deal On Product') ?></strong>        
				<?php 
				} else { ?>    
				    <a href="<?php /* @escapeNotVerified */ echo $block->getDealUrl('mpdailydeal/account/index')?>">
				        <?php /* @escapeNotVerified */ echo __('Add Deal On Product') ?>
				    </a>                
				<?php } ?>
			</li>
			<li class="nav item <?php /* @escapeNotVerified */ echo $block->getCurrentNavClass('mpdailydeal/account/deallist');?>">
				<?php if($block->getCurrentNavClass('mpdailydeal/account/deallist')){ ?>   
				    <strong><?php /* @escapeNotVerified */ echo __('Deal Product List') ?></strong>        
				<?php 
				} else { ?>    
				    <a href="<?php /* @escapeNotVerified */ echo $block->getDealUrl('mpdailydeal/account/deallist')?>">
				        <?php /* @escapeNotVerified */ echo __('Deal Product List') ?>
				    </a>                
				<?php } ?>
			</li>
		</ul>   
	</li>
<?php } ?>