<?php
/**
  * Webkul_MpDailyDeal Deal Link Block.
  * @category  Webkul
  * @package   Webkul_MpDailyDeal
  * @author    Webkul
  * @copyright Copyright (c) 2010-2016 Webkul Software Private Limited (https://webkul.com)
  * @license   https://store.webkul.com/license.html
  */
$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$url = $helper->getRewriteUrl('mpdailydeal/collection/deal/shop/'.$block->getShopUrl());
?>
<div class="section">
    <a class="store-name" href="<?php /* @escapeNotVerified */ echo $url?>">
        <?php /* @escapeNotVerified */ echo __('Deal Collection') ?>
    </a>
</div>