<?php
$_charts = $block->getCharts();
?>

<script type="text/javascript">
    var charts        = [];
    var defaultSeries = <?= json_encode($block->getDefaultSeries()) ?>;

    <?php for ($_idx = 0; $_idx < $_charts; ++$_idx): ?>
    charts.push({
        idx    : <?= $_idx ?>,
        data   : <?= json_encode($block->getDataTable($_idx)) ?>,
        header : '<?= $block->getChartHeader($_idx) ?>',
    });
    <?php endfor ?>

    var options = {
        chartArea: {
            width: '100%',
            height: '70%'
        },

        bar: {
            groupWidth: '80%'
        },

        bars: 'vertical',

        colors: ["#2fd75b", "#c7b700", "#52c4ff", "#ff7e0e", "#aaeeee", "#ff0066", "#eeaaee", "#55BF3B", "#DF5353", "#7798BF", "#aaeeee"],

        fontSize: '11',

        legend: {
            position: 'bottom',
            alignment: 'center',
            textStyle: {
                color    : '#aaaaaa',
                fontSize : '11'
            }
        },

        hAxis: {
            textStyle: {
                color    : '#aaaaaa',
                fontSize : '11'
            },
            slantedText: false,
            maxAlternation: 1
        },

        vAxis: {
            minValue: 0,
            textPosition: 'in',
            baselineColor: '#dddddd',
            gridlines: {
                color: '#f0f0f0'
            },
            textStyle: {
                color    : '#aaaaaa',
            }
        }
    };

    function drawCharts()
    {
        charts.forEach(function(chart) {
            if (chart.data.length <= 1) {
                document.getElementById('chart' + chart.idx).style.display = 'none';
                return;
            }

            chart.data    = google.visualization.arrayToDataTable(chart.data);
            chart.view    = new google.visualization.DataView(chart.data);
            chart.obj     = new google.visualization.ColumnChart(document.getElementById('chart' + chart.idx));
            chart.columns = [];
            chart.series  = {};
            chart.options = Object.clone(options);

            chart.options.title = chart.header;

            for (var i = 0; i < chart.data.getNumberOfColumns(); i++) {
                if (i == 0 || defaultSeries.indexOf(i) > -1) {
                    chart.columns.push(i);
                } else {
                    chart.columns.push({
                        label        : chart.data.getColumnLabel(i),
                        type         : chart.data.getColumnType(i),
                        sourceColumn : i,
                        calc         : function() {
                            return null;
                        }
                    });

                    chart.series[i - 1] = {type: 'line'};
                }

                if (i > 0) {
                    if (chart.series[i - 1] == undefined) {
                        chart.series[i - 1] = {};
                    }

                    if (defaultSeries.indexOf(i) == -1) {
                        chart.series[i - 1].color = '#eeeeee';
                    }
                }
            }

            chart.options.series = chart.series;

            google.visualization.events.addListener(chart.obj, 'select', onSelect);

            chart.view.setColumns(chart.columns);
            chart.obj.draw(chart.view, chart.options);

            function onSelect()
            {
                toggleSeries(chart.obj.getSelection());
            }
        });
    }

    function toggleSeries(selection)
    {
        if (selection.length > 0) {
            if (selection[0].row == null) {
                var col = selection[0].column;

                charts.forEach(function(chart) {
                    if (typeof(chart.columns[col]) == 'number') {
                        var src = chart.columns[col];

                        chart.columns[col] = {
                            label        : chart.data.getColumnLabel(src),
                            type         : chart.data.getColumnType(src),
                            sourceColumn : src,
                            calc         : function () {
                                return null;
                            }
                        };

                        chart.series[src - 1].color = '#eeeeee';
                        chart.series[src - 1].type  = 'line';
                    } else {
                        var src = chart.columns[col].sourceColumn;
                        chart.columns[col] = src;

                        chart.series[src - 1].color = null;
                        chart.series[src - 1].type  = 'column';
                    }

                    var view = new google.visualization.DataView(chart.data);
                    view.setColumns(chart.columns);
                    chart.obj.draw(view, chart.options);
                });
            }
        }
    }
</script>

<?php for ($i = 0; $i < $_charts; ++$i): ?>
    <div id="chart<?= $i ?>" style="widht: 100%; height: 300px;"></div>
<?php endfor ?>
