<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="blog-widget-recent blog-main container-width">
  <div class="row">
 
 
   <div class="content-heading">
    <h2 class="title"><?php echo $block->escapeHtml($block->getTitle()) ?></h2>
	</div>
    <div  class="post-list blog-carousel clearfix">
        <?php foreach ($_postCollection as $_post) { ?>
            <?php
                $_postUrl = $_post->getPostUrl();
                $_postName = $block->escapeHtml($_post->getTitle(), null, true);
            ?>
            <div class="item product-blog-inner post-holder post-holder-<?php echo $_post->getId() ?>">
               
				
				

                <div class="post-content">
                    <div class="post-description clearfix">
                        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                        <div class="post-ftimg-hld image-block">
                            <a class="subimage" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                                <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                            </a>
							<div class="post-image-hover">&nbsp;</div>
							<div class="image-hover-block">
								<a class="zoom lightbox cboxElement" title="Click to zoom the image" data-lightbox="example-set" href="<?php echo $featuredImage ?>">&nbsp;</a> 
								<a class="read" title="Click For Read More" href="<?php echo $_postUrl ?>">&nbsp;</a>
							</div>
							<div class="item post-posed-date">
									<?php /*?><span class="label"><?php echo __('Posted:') ?></span><?php */?>
									<span class="value"><?php echo $_post->getPublishDate('F d, Y') ?></span>
							</div>
                        </div>
                        <?php } ?>
						<div class="post-desc">	
							 <div class="post-title-holder clearfix">
									<div class="post-title">
										<a class="post-item-link" href="<?php echo $_postUrl ?>">
											<?php echo $_postName; ?>
										</a>
									</div>
							</div>
						 
							
							<div class="post-text-hld clearfix">
								<?php 
								$totalword = strlen($block->getShorContent($_post)); 
								if($totalword >= 120){
									$shortdesc = substr($block->getShorContent($_post),0,100)." ...";
									echo $shortdesc;
								}else{
									echo $block->getShorContent($_post);
								}
								
								?>
							</div>
							<a class="post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
							   <?php echo __('Read more &#187;') ?>
							</a>
                    </div>
					</div>
                </div>
                <div class="post-footer">

                </div>
            </div>

        <?php } ?>
    </div>
</div>
</div>
<?php } ?>