<?php $product = $this->getCurrentProduct() ?>
<?php if($product && $product->getCheckDeliveryEnable()==1): ?>
	<form data-mage-init='{"validation": {}}' class="form" id="checkDelivery-form" method="post" autocomplete="off" onSubmit="return checkPostcode()">
	   <fieldset class="fieldset">
		   <legend class="legend"><span><?php echo __('Check Delivery') ?></span></legend><br>
			<div class="field required">
				<label for="delivery_postcode" class="label"><span><?php echo __('Postcode') ?></span></label>
				<div class="control">
					<input type="text" name="postcode" id="delivery_postcode" value="" title="<?php echo __('Postcode') ?>" class="input-text" data-validate="{required:true, 'validate-digits':true}">
				</div>
			</div>
			<div class="message"></div>
	   </fieldset>
	   <div class="actions-toolbar">
			<div class="primary">
				<button type="submit" class="action submit primary" title="<?php  echo __('Check') ?>"><span><?php echo __('Check') ?></span></button>
			</div>
		</div>
	</form>
	<script type="text/x-magento-init">
		{
			"#checkDelivery-form": {
				"validation": {}
			}
		}
	</script>
	<script>
		function checkPostcode() {
			var deliveryMessage = jQuery('#checkDelivery-form .message');
			deliveryMessage.removeClass('success').removeClass('error').hide();
			var deliveryForm = jQuery('#checkDelivery-form');
			if(deliveryForm.valid()) {
				jQuery.ajax({
					type: "POST",
					url: '<?php echo $this->getUrl('checkDelivery/postcode/check',array('id'=>$product->getId())) ?>',
					data: deliveryForm.serialize(),
					dataType: "json",
					showLoader: true,
					success: function(response) {
						deliveryMessage.addClass(response.type).html(response.message).show();
					}
				});
			}
			return false;
		}
	</script>
<?php endif; ?>
