<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAssignProduct
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div class="wk-loading-mask wk-display-none">
    <div class="wk-loader"></div>
</div>
<?php
    $itemWidth = 95.6;
    $productId = $block->getProduct()->getId();
    $helper = $this->helper("Webkul\MpAssignProduct\Helper\Data");
    $marketplaceHelper = $this->helper("Webkul\Marketplace\Helper\Data");
    $cartHelper = $this->helper('Magento\Checkout\Helper\Cart');
    $product = $helper->getProduct($productId);
    $url = $cartHelper->getAddUrl($product);
    $formKey = $helper->getFormKey();
    $allProducts = $block->getAssignedProducts();
    $totalSellers = count($allProducts);
    $dir = $block->getDirection();
    $sortOrder = $block->getSortOrder();
    $defaultUrl = $block->getDefaultUrl();
    $sortOrders = ["price" => "Price",  "rating" => "Rating"];
    $productType = $product->getTypeId();
    if ($productType == "configurable") {
        $isConfig = 1;
    } else {
        $isConfig = 0;
    }
    $jsonResult = [0];
    $btnHtml = "";
    $symbol = $helper->getCurrencySymbol();
    $minPrice = $helper->getMinimumPriceHtml($productId, $productType);
    $totalSellersHtml = "<span>$totalSellers</span>";
    $minPriceHtml = "<span>$minPrice</span>";
    $showProfile = $helper->showProfile();
?>
<?php if (count($allProducts) > 0): ?>
    <div class="wk-ap-list-header" id="wk_list_header">
        <?php if($helper->showMinimumPrice()): ?>
            <?php if ($totalSellers > 1): ?>
                <?php echo __("Sold by %1 more Sellers from %2", $totalSellersHtml, $minPriceHtml); ?>
            <?php else: ?>
                <?php echo __("Sold by %1 more Seller at %2", $totalSellersHtml, $minPriceHtml); ?>
            <?php endif; ?>
        <?php else: ?>
            <?php if ($totalSellers > 1): ?>
                <?php echo __("Sold by %1 more Sellers", $totalSellersHtml); ?>
            <?php else: ?>
                <?php echo __("Sold by %1 more Seller", $totalSellersHtml); ?>
            <?php endif; ?>
        <?php endif; ?>
        
        <div class="toolbar-sorter sorter">
            <label class="sorter-label" for="sorter">Sort By</label>
            <select id="list_sorter" class="sorter-options">
                <?php foreach ($sortOrders as $code => $sOrder):?>
                    <?php if ($sortOrder == $code): ?>
                        <option selected value="<?php echo $code?>"><?php echo __($sOrder); ?></option>
                    <?php else :?>
                        <option value="<?php echo $code?>"><?php echo __($sOrder); ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
            <?php if ($dir == "asc"): ?>
                <a id="list_dir_desc" title="<?php echo __('Set Descending Direction'); ?>" href="#" class="action sorter-action sort-asc">
                    <span><?php echo __('Set Descending Direction'); ?></span>
                </a>
            <?php else: ?>
                <a id="list_dir_asc" title="<?php echo __('Set Ascending Direction'); ?>" href="#" class="action sorter-action sort-desc">
                    <span><?php echo __('Set Ascending Direction'); ?></span>
                </a>
            <?php endif; ?>
        </div>
    </div>
    <div id="product_list" class="wk-ap-product-list wk-ap-fieldset">
        <table class="data table wk-table-product-list">
            <thead>
                <th><?php echo __('Seller'); ?></th>
                <th></th>
                <th><?php echo __('Rating'); ?></th>
                <th><?php echo __('Availability'); ?></th>
                <th><?php echo __('Information'); ?></th>
                <th><?php echo __('Price'); ?></th>
                <th></th>
            </thead>
            <?php foreach ($allProducts as $product): ?>
                <?php
                    $assignId = $product->getId();
                    $price = $this->helper('Magento\Framework\Pricing\Helper\Data')
                                ->currency($product->getPrice(), true, false);
                    $sellerId = $product->getSellerId();
                    $shopTitle = $product->getShopTitle();
                    if (!$shopTitle) {
                        $shopTitle = $product->getShopUrl();
                    }
                    $logo = $product->getLogoPic() != '' ? $product->getLogoPic():"noimage.png";
                    $logo = $this->getUrl('pub/media/').'avatar/'.$logo;
                    $shopUrl = $marketplaceHelper->getRewriteUrl('marketplace/seller/profile/shop/'.$product['shop_url']);
                    $baseImage = $product->getImage();
                    $condition = $product->getCondition();
                    if ($condition == 1) {
                        $condition = "New";
                    } else {
                        $condition = "Used";
                    }
                    $sellerRating = $marketplaceHelper->getFeedTotal($sellerId);
                    $totalCount = $sellerRating['feedcount'];
                    $percent = $sellerRating['totalfeed'];
                    $rate = 0;
                    if ($totalCount > 0) {
                        $rate = $percent / 20;
                        $rate = number_format($rate, 1);
                        $reviewHtml = '<div class="rating-summary">';
                        $reviewHtml .= '<div class="rating-result">';
                        $reviewHtml .= '<span style="width:'.$percent.'%"></span>';
                        $reviewHtml .= '</div>';
                        $reviewHtml .= '</div>';
                        $reviewHtml .= '<div class="wk-ap-rating-info">';
                        $reviewHtml .= '(<span>'.$rate.'</span> based on <span>'.$totalCount.' ratings</span>)';
                        $reviewHtml .= '</div>';
                    } else {
                        $msg = __("Be the first to review");
                        $reviewHtml = '<div class="wk-ap-no-review"><a target="_blank" href="'.$shopUrl.'">'.$msg.'</a></div>';
                    }
                    if ($product->getQty() > 0) {
                        $availability = __("IN STOCK");
                        $availabilityClass = " wk-in-stock";
                        $displyAddToCart = true;
                    } else {
                        $availability = __("OUT OF STOCK");
                        $availabilityClass = " wk-out-of-stock";
                        $displyAddToCart = false;
                    }
                    if ($product->getType() == "configurable") {
                        $availability = "-";
                        $availabilityClass = " wk-in-stock";
                        $displyAddToCart = false;
                        $btnLabel = __('Book Now');
                        $btnHtml = '<input type="number" class="wk-ap-qty input-text qty" title="'.__("Qty").'" value="1" maxlength="12" id="qty" name="qty">';
                        $btnHtml .= '<button data-id="'.$product->getId().'" class="wk-ap-add-to-cart action primary tocart" title="'.$btnLabel.'" type="button">';
                        $btnHtml .= '<span>'.$btnLabel.'</span>';
                        $btnHtml .= '</button>';
                        $associatedOptions = $helper->getAssociatedOptions($productId);
                        $jsonResult = $associatedOptions;
                    }
                    
                    $collectionUrl = $this->getUrl("marketplace/seller/collection")."shop/".$product->getShopUrl();
                    $images = $helper->getImagesCollection($assignId);
                    $baseImageUrl = $helper->getBaseImageUrl($assignId);
                    $mainHtml = "";
                    $galleryHtml = "";
                    $galleryCount = 0;
                    $activeGallery = 0;
                    $tmpHtml = "";
                    foreach ($images as $image) {
                        $galleryCount++;
                        $class = "";
                        if ($galleryCount == 1) {
                            $class = "firstItem";
                            $tmpHtml .= "<img src='".$baseImageUrl.$image->getValue()."'>";
                        }
                        if ($image->getId() == $baseImage) {
                            $mainHtml .= "<img src='".$baseImageUrl.$image->getValue()."'>";
                            $galleryHtml .= "<div data-id='".$galleryCount."' class='wk-ap-product-showcase-gallery-item wk-ap-active ".$class."'><img src='".$baseImageUrl.$image->getValue()."'></div>";
                            $activeGallery = $galleryCount;
                        } else {
                            $galleryHtml .= "<div data-id='".$galleryCount."' class='wk-ap-product-showcase-gallery-item ".$class."'><img src='".$baseImageUrl.$image->getValue()."'></div>";
                        }
                    }
                    if ($mainHtml == "") {
                        $mainHtml = $tmpHtml;
                        $galleryHtml = str_replace("firstItem", "wk-ap-active", $galleryHtml);
                    } else {
                        $galleryHtml = str_replace("firstItem", "", $galleryHtml);
                    }
                    $width = $galleryCount*$itemWidth;
                    if ($activeGallery > 5) {
                        $left = $activeGallery - 5;
                        $left = $left*$itemWidth;
                    } else {
                        $left = 0;
                    }
                    $showNavigation = false;
                    if ($galleryCount > 5) {
                        $showNavigation = true;
                    }
                ?>
                <tr data-id="<?php echo $product->getId();?>">
                    <td class="col wk-ap-img-col3">
                        <div class="wk-ap-seller-info">
                            <a class="wk-ap-shop-link" title="<?php echo $shopTitle; ?>" target="_blank" href="<?php echo $shopUrl; ?>">
                                <img src="<?php echo $logo; ?>" />
                            </a>
                        </div>
                    </td>
                    <td class="col col wk-ap-img-col2">
                        <?php if ($showProfile): ?>
                            <span class="wk-ap-shop-title">
                                <a class="wk-ap-shop-link" title="<?php echo $shopTitle; ?>" target="_blank" href="<?php echo $shopUrl; ?>">
                                    <?php echo $shopTitle; ?>
                                </a>
                            </span>
                            <span class="wk-ap-shop-products">
                                <a class="wk-ap-shop-link" target="_blank" href="<?php echo $collectionUrl; ?>">
                                    <?php echo __("View Products"); ?>
                                </a>
                            </span>
                        <?php endif; ?>
                    </td>
                    <td class="col">
                        <?php echo $reviewHtml; ?>
                    </td>
                    <td class="col wk-ap-product-avl"><?php echo $availability; ?></td>
                    <td class="col wk-ap-info-wrap">
                        <div class="wk-ap-condition-label <?php echo "wk-ap-".$condition.$availabilityClass; ?>">
                            <?php echo __($condition); ?>
                        </div>
                        <div class="wk-ap-product-info">
                            &#8505;
                            <div class="wk-ap-product-info-content">
                                <?php echo $product->getDescription(); ?>
                            </div>
                        </div>
                        <?php if ($galleryCount > 0): ?>
                            <div class="wk-ap-product-image-panel">
                                <div class="wk-ap-product-image">
                                    <div class="wk-ap-product-image-inner"></div>
                                </div>
                                <div class="wk-ap-product-image-content">
                                    <div class="wk-ap-product-showcase">
                                        <div class="wk-ap-product-showcase-main">
                                            <?php echo $mainHtml; ?>
                                        </div>
                                        <?php if ($galleryCount > 1): ?>
                                            <div class="wk-ap-product-showcase-gallery">
                                                <?php if ($showNavigation): ?>
                                                    <div class="wk-ap-gallery-navigation wk-gallery-left">
                                                        <div class="wk-ap-gallery-navigation-left"></div>
                                                    </div>
                                                <?php endif; ?>
                                                <div class="wk-ap-product-showcase-gallery-viewport">
                                                    <div data-count="<?php echo $galleryCount; ?>" class="wk-ap-product-showcase-gallery-wrap" style="width:<?php echo $width; ?>px; left:-<?php echo $left; ?>px;">
                                                        <?php echo $galleryHtml; ?>
                                                    </div>
                                                </div>
                                                <?php if ($showNavigation): ?>
                                                    <div class="wk-ap-gallery-navigation wk-gallery-right">
                                                        <div class="wk-ap-gallery-navigation-right"></div>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>
                    </td>
                    <td class="col">
                        <span class="wk-ap-product-price"><?php echo $price; ?></span>
                    </td>
                    <td class="col wk-ap-action-col">
                        <?php if ($displyAddToCart): ?>
                            <input type="number" class="wk-ap-qty input-text qty" title="<?php echo __('Qty'); ?>" value="1" maxlength="12" id="qty" name="qty">
                            <button data-id="<?php echo $product->getId();?>" class="wk-ap-add-to-cart action primary tocart" title="<?php echo __('Add to Cart'); ?>" type="button">
                                <span><?php echo __('Booking Now'); ?></span>
                            </button>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
    <?php
        $data = [];
        $data["isConfig"] = $isConfig;
        $data["productId"] = $productId;
        $data["formKey"] = $formKey;
        $data["url"] = $url;
        $data["dir"] = $dir;
        $data["defaultUrl"] = $defaultUrl;
        $data["sortOrder"] = $sortOrder;
        $data["btnHtml"] = $btnHtml;
        $data["url"] = $url;
        $data["jsonResult"] = $jsonResult;
        $data["symbol"] = $symbol;
        $data["itemWidth"] = $itemWidth;
        $data = json_encode($data);
    ?>
    <script type="text/x-magento-init">
        {
            "body": {
                "Webkul_MpAssignProduct/js/assignproduct": <?php echo $data ?>
            }
        }
    </script>
<?php endif; ?>