<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAssignProduct
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
	$helper = $this->helper("Webkul\MpAssignProduct\Helper\Data");
	$queryString = $helper->getQueryString();
	$isPartner = $this->helper('Webkul\Marketplace\Helper\Data')->isSeller();
	$collection = $this->getAllProducts();
	$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
	$editAction = $this->getUrl('mpassignproduct/product/edit');
	$deleteAction = $this->getUrl('mpassignproduct/product/delete');
	$url = $this->getUrl('mpassignproduct/product/massdelete');

?>
<?php if($isPartner == 1): ?>
	<?php if($collection->getSize()): ?>
		<fieldset class="fieldset">
			<div class="wk-mp-page-title page-title">
			<h2>
				<span><?php echo __("My Products"); ?></span>
			</h2>
		</div>
			<form method="post" action="<?php echo $url; ?>" id="wk_mpassignproduct_delete_form">
				<div class="table-responsive">
			<table class="table table-striped table-bordered table-hover">
					<thead>
						<th width="100px">
							<button title="<?php echo __('Delete'); ?>" class="wk-ap-del action primary">
								<span><?php echo __("Delete"); ?></span>
							</button>
						</th>
						<th><?php echo __("Image"); ?></th>
						<th><?php echo __("Name"); ?></th>
						<th><?php echo __("Price"); ?></th>
						<th><?php echo __("Qty"); ?></th>
						<th><?php echo __("Status"); ?></th>
					
						<th><?php echo __("Action"); ?></th>
					</thead>
					<?php foreach ($collection as $product): ?>
						<?php
							$_product = $helper->getProduct($product->getProductId());


							
    
						    $image = 'category_page_list';
						    $productImage = $_imagehelper->init($_product, $image)
                                ->constrainOnly(FALSE)
                                ->keepAspectRatio(TRUE)
                                ->keepFrame(FALSE)
                                ->resize(300)
                                ->getUrl();




							$name = $_product->getName();
							$price = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($product->getPrice(), true, false);
							$condition = $product->getCondition();
							if($condition == 1) {
								$condition = "New";
							} else {
								$condition = "Used";
							}
							$status = $product->getStatus();
							if($status == 1) {
								$status = "Approved";
							} else {
								$status = "Unapproved";
							}
							$fullDescription = $product->getDescription();
							if(strlen($fullDescription) > 20) {
								$description = substr($fullDescription, 0, 19)."...";
							} else {
								$description = $fullDescription;
							}
							
						?>
						<tr>
							<td class="col"><input class="wk-ap-del-chkbox" type="checkbox" name="wk_delete[]" value="<?php echo $product->getId(); ?>"></td>
							<td class="col"><img class="wk-ap-img2" src="<?php echo $productImage; ?>" /></td>
							<td data-title="<?php echo __("Name"); ?>" class="col"><a class="wk-ap-pn" href="<?php echo $_product->getProductUrl(); ?>" target="_blank"><?php echo $name; ?></a></td>
							
							<td data-title="<?php echo __("Price"); ?>" class="col"><?php echo $price; ?></td>
							<td data-title="<?php echo __("Quantity"); ?>" class="col"><?php echo $product->getQty(); ?></td>
							
							<td data-title="<?php echo __("Status"); ?>" class="col"><?php echo __($status); ?></td>							<td class="col">
								<span class="wk-ap-edit-item" data-id="<?php echo $product->getId(); ?>"></span>
								<span class="wk-ap-delete-item" data-id="<?php echo $product->getId(); ?>"></span>
							</td>
						</tr>
					<?php endforeach; ?>
				</table>
			</div>
			</form>
		</fieldset>
	<?php else: ?>
		<div class="wk-mp-page-title page-title">
			<h2>
				<span><?php echo __("My Products"); ?></span>
			</h2>
		</div>
		<div>
			<br/>
			<b>
			<?php echo __("No Product Found"); ?></b>
		</div>
	<?php endif ?>
	<?php if ($block->getPagerHtml()): ?>
		<div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
	<?php endif ?>
<?php else: ?>
	<h2 class="wk-mp-error-msg">
		<?php echo __("To Become Seller Please Contact to Admin."); ?>
	</h2>
<?php endif; ?>
<?php
	$data = [];
	$data["editTitle"] = __('Do you want to edit?');
	$data["editAction"] = $editAction;
	$data["deleteTitle"] = __('Do you want to delete product?');
	$data["deleteAction"] = $deleteAction;
	$data["msg"] = __('Please select products to delete.');
	$data = json_encode($data);
?>
<script type="text/x-magento-init">
	{
		"body": {
			"Webkul_MpAssignProduct/js/list": <?php echo $data ?>
		}
	}
</script>
