<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile
?>
<img src="<?php echo $block->getSellerStatisticsGraphUrl(true) ?>" alt="Seller Statistics Graph" title="Seller Statistics Graph" id="wk-diagram-chart"/>