<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile

/** @var $block \Webkul\Marketplace\Block\Account\Editprofile */ 

$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$partner=$helper->getSeller();
$profile_hint_status = $helper->getProfileHintStatus();
?>
<form action="<?php echo $block->getUrl('marketplace/account/editProfilePost', ["_secure" => $this->getRequest()->isSecure()]) ?>" enctype="multipart/form-data" method="post" data-role="form-profile-validate" data-mage-init='{"validation":{}}'>
	<div class="wk-mp-page-title page-title">
		<h2><?php echo __('Edit Profile Information') ?></h2>
		<button class="btn btn-rounded btn-green btn-small pull-right" title="<?php echo __('Save Profile') ?>" type="submit" id="save-btn">
			<span><span><?php echo __('Save Profile') ?></span></span>
		</button>
	</div>
	<?php echo $block->getBlockHtml('formkey')?>
	<div class="wk-mp-design">
		<fieldset class="fieldset info wk-mp-fieldset">
			<legend class="legend"><span><?php echo __('Profile Information') ?></span></legend>
		
		<div class="row ">
			
			<div class="field profile col-xs-6">
				<label for="company_locality"><?php echo __('Postal Code') ?></label>
				
				<?php
				$i=0;
				$slocation=explode(",",$partner['company_locality']);
				if(count($slocation)>0)
				foreach($slocation as $l){?>
				<br/>
				    <div class="control">
    					 <input type="text" id="company_locality<?=$i;?>" name="company_locality[]" value="<?php echo $l; ?>" title="company_locality" class="input-text number" placeholder="Postcode " minlength="4"  maxlength="4" />
    					 <?php if($i==0):?><button type="button" id="addSubharb" >+</button><?php endif;$i++; ?>
    				</div>
    				
				    <?php
				}
				else{
				?>
    				<div class="control">
    					 <input type="text" id="company_locality<?=$i;?>" name="company_locality[]" value="" title="company_locality" class="input-text number" placeholder="Postcode " minlength="4" maxlength="4"   /> <button type="button" id="addSubharb">+</button>
    				</div>
				<?php
				}
				?>
				<div class="loadedmore"></div>
			
			<script>
			var max=15;
				    jQuery("#addSubharb").on("click",function(){
				        if(max>0)
				        jQuery(".loadedmore").append('<br/> <div class="control"><input type="text" id="company_locality" name="company_locality[]" value="" title="company_locality" class="input-text number" placeholder="Postcode " minlength="4"  maxlength="4" /></div>');
				        max--;
				        
				    });
				</script>
			
			</div>
			
			
		</div>
			<hr/>

								
			<div class="field profile">
				<label for="logo-pic"> <?php echo __('Company Logo') ?> </label>
				<?php
				if($profile_hint_status && $helper->getProfileHintLogo()){?>
					<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProfileHintLogo() ?>"/>
				<?php
				} ?>
				<div class="control">
					<input type="file" id="logo-pic" alt="no image" name="logo_pic" title="<?php echo __('Seller Logo')?>" class="input-text banner" size="26"/>
					<div class="logoimage-set">
					  	<div class="setimage">
							<img class="prev-img" src="<?php echo $helper->getMediaUrl().'avatar/'.$partner['logo_pic']; ?>"/>
							<?php
							$logopic = $partner['logo_pic']; 
							if($logopic){
							?>
								<span class="wk-logoimagedelete" title="<?php echo __('Delete')?>">
								  	<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/deleteIcon.png'); ?>" alt="<?php echo __('Delete Image')?>" title="<?php echo __('Delete Image')?>"/>
								</span>
							<?php
							}?>
						</div>
					</div>
				</div>
			</div>
			
			
			<?php
			if($helper->getSellerPolicyApproval()){?>
				<div class="field profile">
					<label><?php echo __('Vendor Terms & Conditions') ?></label>
					<?php
					if($profile_hint_status && $helper->getProfileHintReturnPolicy()){?>
						<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProfileHintReturnPolicy() ?>"/>
					<?php
					} ?>
					<div class="control">
						 <textarea type="text" id="return_policy" name="return_policy"  rows="5"  title="return_policy" class="input-text compdesi" ><?php echo $partner['return_policy']; ?> </textarea>
					</div>
				</div>
			<input type="hidden" value="" id="shipping_policy" name="shipping_policy"/>
			<?php
			} ?>
			<script>
				require([
				    'jquery',
				    'mage/adminhtml/wysiwyg/tiny_mce/setup'
				], function(jQuery){

					var config = '<?php echo $block->getWysiwygConfig() ?>',
					    editor;

					jQuery.extend(config, {
					    settings: {
					        theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
					            'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
					        theme_advanced_buttons2: null,
					        theme_advanced_buttons3: null,
					        theme_advanced_buttons4: null,
					        theme_advanced_statusbar_location: null
					    },
					    files_browser_window_url: false
					});

				
				    <?php
					if( $helper->getSellerPolicyApproval()){?>
						editor = new tinyMceWysiwygSetup(
						    'return_policy',
						    config
						);
						editor.turnOn();
					    jQuery('#return_policy')
					    .addClass('wysiwyg-editor')
					    .data(
					        'wysiwygEditor',
					        editor
					    );

					   
					<?php
					} ?>
				});
				</script>
			    <div class="field profile">
					<label><?php echo __('Turn Product On/Off') ;
					?></label>
				
				<div class="control">
					 <input type="radio"  name="visibility"  title="Product Visibility" class="input-radio" value="1" <?=($partner['visibility']==1)?'checked="checked"':'';?> /> On <input type="radio" name="visibility" title="Disable Product Visibility" class="input-radio" value="0"  <?=($partner['visibility']==0)?'checked="checked"':'';?>  /> Off 

				</div>

				
				</div>
		</fieldset>
	</div>
</form>
<?php
if(false && $helper->getUrlRewrite()){ ?>
	<br/><br/>
	<form action="<?php echo $block->getUrl('marketplace/account/rewriteUrlPost', ["_secure" => $this->getRequest()->isSecure()]) ?>" enctype="multipart/form-data" method="post" data-role="form-urlrewrite-validate" data-mage-init='{"validation":{}}'>
		<div class="page-title" style="width:100%;display:inline-block;">
		<h2 style="float:left;"><?php echo __('Manage Your Shop Url') ?></h1>
			<button class="btn btn-rounded btn-green btn-small pull-right" title="<?php echo __('Set Your New Shop Url') ?>" type="submit" style="float:right;">
				<span><span><?php echo __('Save Url') ?></span></span>
			</button>
		</div>
		<?php echo $block->getBlockHtml('formkey')?>
		<div class="wk-mp-design">
			<fieldset class="fieldset info wk-mp-fieldset">
				<legend class="legend"><span><?php echo __('Edit Your Shop Url') ?></span></legend>
				<div class="field">
					<label><?php echo __('Profile Page Target Url Path') ?></label>
					<div class="control">
						<input type="text" class="input-text" value="<?php echo 'marketplace/seller/profile/shop/'.$partner['shop_url'] ?>" readonly/>
					</div>
				</div>
				<div class="field">
					<label><?php echo __('Profile Page Request Url Path') ?></label>
					<div class="control">
						<input type="text" class="input-text" name="profile_request_url" id="profile_request_url" value="<?php echo $helper->getRewriteUrlPath('marketplace/seller/profile/shop/'.$partner['shop_url']) ?>"/>
					</div>
				</div>
				<div class="field">
					<label><?php echo __('Collection Page Target Url Path') ?></label>
					<div class="control">
						<input type="text" class="input-text" value="<?php echo 'marketplace/seller/collection/shop/'.$partner['shop_url'] ?>" readonly/>
					</div>
				</div>
				<div class="field">
					<label><?php echo __('Collection Page Request Url Path') ?></label>
					<div class="control">
						<input type="text" class="input-text" name="collection_request_url" id="collection_request_url" value="<?php echo $helper->getRewriteUrlPath('marketplace/seller/collection/shop/'.$partner['shop_url']) ?>"/>
					</div>
				</div>
				<div class="field">
					<label><?php echo __('Review Page Target Url Path') ?></label>
					<div class="control">
						<input type="text" class="input-text" value="<?php echo 'marketplace/seller/feedback/shop/'.$partner['shop_url']; ?>" readonly/>
					</div>
				</div>
				<div class="field">
					<label><?php echo __('Review Page Request Url Path') ?></label>
					<div class="control">
						<input type="text" class="input-text" name="review_request_url" id="review_request_url" value="<?php echo $helper->getRewriteUrlPath('marketplace/seller/feedback/shop/'.$partner['shop_url']) ?>"/>
					</div>
				</div>
				<div class="field">
					<label><?php echo __('Location Page Target Url Path') ?></label>
					<div class="control">
						<input type="text" class="input-text" value="<?php echo 'marketplace/seller/location/shop/'.$partner['shop_url']; ?>" readonly/>
					</div>
				</div>
				<div class="field">
					<label><?php echo __('Location Page Request Url Path') ?></label>
					<div class="control">
						<input type="text" class="input-text" name="location_request_url" id="location_request_url" value="<?php echo $helper->getRewriteUrlPath('marketplace/seller/location/shop/'.$partner['shop_url']) ?>"/>
					</div>
				</div>	
			</fieldset>
		</div>	
	</form>
<?php
}
?>
<br/><br/>
<form action="<?php echo $block->getUrl('marketplace/account/savePaymentInfo', ["_secure" => $this->getRequest()->isSecure()]) ?>" enctype="multipart/form-data" method="post" data-role="form-payment-validate" data-mage-init='{"validation":{}}'>
	<div class="wk-mp-page-title page-title">
		<h2><?php echo __('Edit Payment Information') ?></h1>
		<button class="btn btn-rounded btn-green btn-small pull-right" title="<?php echo __('Save Payment') ?>" type="submit">
			<span><span><?php echo __('Save Payment') ?></span></span>
		</button>
	</div>
	<?php echo $block->getBlockHtml('formkey')?>
	<div class="wk-mp-design">
		<fieldset class="fieldset info wk-mp-fieldset">
			<legend class="legend"><span><?php echo __('Payment Information') ?></span></legend>
			<div class="field">
				
				
				<div class="field">
					<label><?php echo __('BSB') ?></label>
					<div class="control">
						<input type="text" class="input-text" name="bsb" id="BSB" value="<?php echo $partner['bsb'] ?>"/>
					</div>
				</div>
				<div class="field">
					<label><?php echo __('Account Number') ?></label>
					<div class="control">
						<input type="text" class="input-text" name="acc_number" id="Account_Number" value="<?php echo $partner['acc_number'] ?>"/>
					</div>
				</div>
				<div class="field">
					<label><?php echo __('Account Name') ?></label>
					<div class="control">
						<input type="text" class="input-text" name="acc_name" id="acc_name" value="<?php echo $partner['acc_name'] ?>"/>
					</div>
				</div>

			</div>
		</fieldset>		
	</div>		
</form>
<br/><br/>
<?php echo $block->getChildHtml(); ?>

<div class="buttons-set">
	<p class="back-link">
		<br/>
	</p>
</div>
<?php
$formData = [
    'countryPicSelector' => '#country-pic',
    'countryImgPrevSelector' => '.country_img_prev',
    'countryLatitudeSelector' => '#country-latitude',
    'countryLongitudeSelector' => '#country-longitude',
    'countryImgPrev' => $this->getViewFileUrl("Webkul_Marketplace::images/country/countryflags/"),
    'backgroundWidthSelector' => '#background_width',
    'logoPicSelector' => '#logo-pic',
    'bannerPicSelector' => '#banner-pic',
    'leftButtonSelector' => '.left',
    'buttonsSetLastSelector' => '.buttons-set:last',
    'inputTextSelector' => '.input-text',
    'profileimageSetSpanSelector' => '.profileimage-set span',
    'bannerSelector' => '.wk-banner',
    'bannerDeleteAjaxUrl' => $block->getUrl('marketplace/account/deleteSellerBanner', ['_secure' => $this->getRequest()->isSecure()]),
    'setimageSelector' => '.setimage',
    'profileImageDeleteSelector' => '.wk-profileimagedelete img',
    'logoImageSetSpanSelector' => '.logoimage-set span',
    'logoSelector' => '.wk-logo',
    'logoDeleteAjaxUrl' => $block->getUrl('marketplace/account/deleteSellerLogo', ['_secure' => $this->getRequest()->isSecure()]),
    'logoImageDeleteSelector' => '.wk-logoimagedelete img'
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>

<script type="text/x-magento-init">
    {
        "*": {
            "editSellerProfile": <?php /* @noEscape */ echo $serializedFormData; ?>
        }

    }
</script>
<script type="text/javascript">
	jQuery("input[type='file']").each(function(){
	jQuery(this).wrap( "<div class='custom-file-choosen'><span class='hide'></span><input type='button' class='btn btn-file btn-primary' value='Browse'/><span class='file-name'>"+jQuery(this).val()+"</span></div>" );
});
jQuery(".btn.btn-file.btn-primary").on("click",function(){
	jQuery(this).parent().find("input[type='file']").trigger("click");
});
jQuery("input[type='file']").on("change",function(){

	jQuery(this).parent().parent().find(".file-name").html(jQuery(this).val().replace("fakepath", "..."));
});

</script>