<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile
// updated file to add notification for seller.
$_helper = $this->helper('Webkul\Marketplace\Helper\Data');
$isPartner= $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
$allow_pro_type=$_helper->getAllowedProductType();
$isSellerGroup = $_helper->isSellerGroupModuleInstalled();
$productNotificationCount = $block->getProductNotificationCount();
$orderNotificationCount = $block->getOrderNotificationCount();
$transactionCount = $block->getTransactionNotificationCount();
?>
<?php 
if($isPartner){ ?>
   <?php if(($isSellerGroup && $_helper->isAllowedAction('marketplace/account/dashboard')) || !$isSellerGroup) { ?>
<style type="text/css">
    @media only screen and (max-width: 767px){

        .block-collapsible-nav.wk-mp-main{
            top: 20px;
        }
    }
</style>
<div class="block account-nav block-collapsible-nav wk-mp-main">
    <div class="title block-collapsible-nav-title" data-mage-init='{"toggleAdvanced": {"toggleContainers": "#block-collapsible-nav-seller", "selectorsToggleClass": "active"}}'>
        <strong><?php /* @escapeNotVerified */ echo __('Marketplace'); ?></strong>
    </div>
    <div class="content block-collapsible-nav-content" id="block-collapsible-nav-seller">
        <nav class="account-nav">
            <ul class="nav items">
                
                        <li class="nav item <?php echo strpos($magentoCurrentUrl,'marketplace/account/dashboard')? "current":"";?>">
                            <?php 
                            if(strpos($magentoCurrentUrl,'marketplace/account/dashboard') !== false){ ?>      
                                <strong><?php echo __('Vendor Dashboard') ?></strong>              
                            <?php
                            } else{ ?>        
                                <a href="<?php echo $block->getUrl('marketplace/account/dashboard', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                    <?php echo __('Vendor Dashboard') ?>
                                </a>                    
                            <?php 
                            } ?>
                        </li>
                    <?php 
                    } ?>
                    <?php if(($isSellerGroup && $_helper->isAllowedAction('marketplace/account/editprofile')) || !$isSellerGroup) { ?>
                        <?php if ($_helper->getSellerProfileDisplayFlag()) { ?>
                            <li class="nav item <?php echo strpos($magentoCurrentUrl,'marketplace/account/editprofile')? "current":"";?>">     
                                <?php if(strpos($magentoCurrentUrl,'marketplace/account/editprofile') !== false){ ?>
                                    <strong><?php echo __('Vendor Profile') ?></strong>
                                <?php 
                                } else{ ?>
                                    <a href="<?php echo $block->getUrl('marketplace/account/editprofile', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                        <?php echo __('Vendor Profile') ?>
                                    </a>
                                <?php 
                                } ?>
                            </li>
                        <?php } ?>
                    <?php } ?>
                    <?php if((($isSellerGroup && $_helper->isAllowedAction('marketplace/product_attribute/new')) || !$isSellerGroup) && false ) {
                        if(strpos($allow_pro_type,'configurable') !== false){ ?>
                            <li class="nav item <?php echo strpos($magentoCurrentUrl,'marketplace/product_attribute/new')? "current":"";?>">       
                            <?php if(strpos($magentoCurrentUrl,'marketplace/product_attribute/new') !== false){ ?>
                                <strong><?php echo __('Create Attribute') ?></strong>  
                                <?php }     
                                else{ ?>        
                                    <a href="<?php echo $block->getUrl('marketplace/product_attribute/new', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                        <?php echo __('Create Attribute') ?></a>           
                                <?php } ?>              
                            </li>
                            <?php
                        }
                    } ?>
                    
                    <li class="nav item <?php echo (strpos($magentoCurrentUrl,'mpassignproduct/product/view/'))? "current":"";?>">
                        <a href="<?php echo $block->getUrl('mpassignproduct/product/view/', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                    <?php echo __('Add new product') ?>
                                </a>  

                    </li>

                    <li class="nav item <?php echo (strpos($magentoCurrentUrl,'mpassignproduct/product/productlist/'))? "current":"";?>">
                        <a href="<?php echo $block->getUrl('mpassignproduct/product/productlist/', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                    <?php echo __('Products List') ?>
                                </a>  

                    </li>

                    <?php if((($isSellerGroup && $_helper->isAllowedAction('marketplace/product/add')) || !$isSellerGroup) && false) { ?>
                        <li class="nav item <?php echo (strpos($magentoCurrentUrl,'marketplace/product/add')||strpos($magentoCurrentUrl,'marketplace/product/create'))? "current":"";?>">           
                            <?php 
                            if(strpos($magentoCurrentUrl,'marketplace/product/add') !== false || strpos($magentoCurrentUrl,'marketplace/product/create') !== false){ ?>       
                                <strong><?php echo __('New Products') ?></strong>  
                            <?php 
                            } else{ ?>                    
                                <a href="<?php echo $block->getUrl('marketplace/product/create', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                    <?php echo __('New Products') ?>
                                </a>                        
                            <?php 
                            } ?>          
                        </li>   
                    <?php } ?>
                    <?php if((($isSellerGroup && $_helper->isAllowedAction('marketplace/product/productlist')) || !$isSellerGroup) && false) { ?>
                        <li class="nav item notification-link <?php echo strpos($magentoCurrentUrl,'marketplace/product/productlist')? "current":"";?>">         
                        <?php if(strpos($magentoCurrentUrl,'marketplace/product/productlist') !== false){ ?>       
                            <strong><?php echo __('My Products List') ?></strong>  
                            <?php }                 
                            else{ ?>                    
                                <a href="<?php echo $block->getUrl('marketplace/product/productlist', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                    <?php echo __('My Products List') ?>
                                </a>
                                <!-- Product Notification -->
                                <?php if ($block->getProductCollection()->getSize()) { ?>
                                <div class="notification-block">
                                    <a href="" class="notifications-action marketplace-dropdown">
                                        <img height="20" width="20" src="<?php echo $block->getViewFileUrl('Webkul_Marketplace::images/icons_notifications.png'); ?>" class="notifications-img" />
                                        <?php if($productNotificationCount > 5): ?>
                                            <span class="notification-count">5+</span>
                                        <?php else: ?>
                                            <span class="notification-count"><?php echo $productNotificationCount; ?></span>
                                        <?php endif; ?>
                                    </a>
                                    <ul class="marketplace-dropdown-menu">
                                    <span class="notify-point"></span>
                                    <?php 
                                    $productDisplayCount = 1;
                                    foreach($block->getProductCollection() as $product): 
                                        if($productDisplayCount <= 5):
                                    ?>
                                    <li class="notifications-entry">
                                        <strong class="notifications-entry-title">
                                            <?php echo $block->getProductNotificationTitle($product->getMageproductId(), $product->getStatus()); ?> 
                                        </strong>
                                        <p class="notifications-entry-description _cutted">
                                            <a href="<?php echo $block->getUrl('marketplace/product/productlist', ['_secure' => $this->getRequest()->isSecure()])?>" class="notifications-entry-description-start">
                                                <span >
                                                    <?php echo $block->getProductNotificationDesc($product->getMageproductId(), $product->getStatus()); ?>
                                                    
                                                </span>
                                            </a>
                                        </p>
                                        <time class="notifications-entry-time">
                                            <?php echo $block->getProductNotifyDateTime($product->getUpdatedAt()); ?>
                                        </time>
                                    </li>
                                <?php  $productDisplayCount++;
                                        endif;
                                    endforeach; ?>
                                    <?php 
                                        if($productDisplayCount > 5):
                                    ?>    
                                            <li class="notifications-entry notifications-entry-last">
                                                <a href="<?php echo $block->getUrl('marketplace/product/productlist', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                                    <?php echo __('Click here to view product list'); ?>
                                                </a>
                                            </li>
                                    <?php endif; ?>
                                    </ul>
                                </div>
                                <?php } ?>
                                <!-- Product Notification End -->
                            <?php } ?>          
                        </li>
                    <?php } ?>
                    <?php if(($isSellerGroup && $_helper->isAllowedAction('marketplace/transaction/history')) || !$isSellerGroup) { ?>
                        <li class="nav item notification-link <?php echo strpos($magentoCurrentUrl,'marketplace/transaction/history')? "current":"";?>">
                            <?php 
                            if(strpos($magentoCurrentUrl,'marketplace/transaction/history') !== false){ ?>
                                <strong><?php echo __('My Transaction List') ?></strong>
                            <?php 
                            } else{ ?>
                                <a href="<?php echo $block->getUrl('marketplace/transaction/history', ['_secure' => $this->getRequest()->isSecure()]); ?>"><?php echo __('My Transaction List') ?></a>
                                <!-- Transaction Notification -->
                                <?php if ($block->getTransactionCollection()->getSize()) { ?>
                                <div class="notification-block">
                                    <a href="" class="notifications-action marketplace-dropdown">
                                        <img height="20" width="20" src="<?php echo $block->getViewFileUrl('Webkul_Marketplace::images/icons_notifications.png'); ?>" class="notifications-img" />
                                    <?php if($transactionCount > 5): ?>
                                        <span class="notification-count">5+</span>
                                    <?php else: ?>
                                        <span class="notification-count"><?php echo $transactionCount; ?></span>
                                    <?php endif; ?>
                                    </a>
                                    <ul class="marketplace-dropdown-menu">
                                    <span class="notify-point"></span>
                                    <?php
                                    $trnDisplayCount = 1;
                                    foreach($block->getTransactionCollection() as $transaction): 
                                        if($trnDisplayCount <= 5):
                                        ?>
                                        <li class="notifications-entry">
                                            <strong class="notifications-entry-title">
                                                <?php echo $block->getTransactionNotifyTitle($transaction->getEntityId()); ?> 
                                            </strong>
                                            <p class="notifications-entry-description _cutted">
                                                <a href="<?php echo $block->getUrl('marketplace/transaction/view', ['id'=>$transaction->getId(), 'n' => 1, '_secure' => $this->getRequest()->isSecure()])?>" class="notifications-entry-description-start">
                                                    <span>
                                                        <?php echo $block->getTransactionNotifyDesc($transaction->getEntityId()); ?>
                                                    </span>
                                                </a>
                                            </p>
                                            <time class="notifications-entry-time">
                                                <?php echo $block->getTransactionDate($transaction->getUpdatedAt()); ?>
                                            </time>
                                        </li>
                                    <?php $trnDisplayCount++;
                                        endif; 
                                    endforeach; ?>
                                        
                                    <?php
                                        if($trnDisplayCount > 5):
                                    ?> 
                                            <li class="notifications-entry notifications-entry-last">
                                               <a href="<?php echo $block->getUrl('marketplace/transaction/history', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                                    <?php echo __('Click here to view transaction history'); ?>
                                                </a>
                                            </li>
                                    <?php endif; ?>
                                    </ul>
                                </div>
                                <?php } ?>
                                <!-- Transaction Notification End -->
                            <?php 
                            } ?>
                        </li>
                    <?php } ?>
                    <?php if(($isSellerGroup && $_helper->isAllowedAction('marketplace/order/shipping')) || !$isSellerGroup) { ?>
                        <?php if($_helper->getIsOrderManage()=="1") {?>
                        <li class="nav item <?php echo strpos($magentoCurrentUrl,'marketplace/order/shipping/')? "current":"";?>">
                            <?php if(strpos($magentoCurrentUrl,'marketplace/order/shipping') !== false){ ?>
                                <strong><?php echo __('Manage Print PDF Header Info') ?></strong>
                            <?php 
                            } else{ ?>
                                <a href="<?php echo $block->getUrl('marketplace/order/shipping', ['_secure' => $this->getRequest()->isSecure()]); ?>"><?php echo __('Manage Print PDF Header Info') ?></a>
                            <?php 
                            } ?>
                        </li>
                        <?php 
                        } ?>
                    <?php } ?>    
                    <?php echo $block->getChildHtml();?>
                    <?php if(($isSellerGroup && $_helper->isAllowedAction('marketplace/order/history')) || !$isSellerGroup) { ?>
                        <li class="nav item notification-link  <?php echo strpos($magentoCurrentUrl,'marketplace/order')&&(!strpos($magentoCurrentUrl,'marketplace/order/shipping/'))? "current":"";?>">        
                            <?php 
                            if(strpos($magentoCurrentUrl,'marketplace/order') !== false && strpos($magentoCurrentUrl,'marketplace/order/shipping/') === false){ ?>    
                                <strong><?php echo __('My Order History') ?></strong>  
                            <?php 
                            } else{ ?>        
                                <a href="<?php echo $block->getUrl('marketplace/order/history', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                    <?php echo __('My Order History') ?>
                                </a>
                                <?php if ($block->getMarketplaceOrderCollection()->getSize()) { ?>
                                <!-- Orders Notification -->
                                <div class="notification-block">
                                    <a href="" class="notifications-action marketplace-dropdown">
                                        <img height="20" width="20" src="<?php echo $block->getViewFileUrl('Webkul_Marketplace::images/icons_notifications.png'); ?>" class="notifications-img" />
                                        <?php if($orderNotificationCount > 5): ?>
                                        <span class="notification-count">5+</span>
                                        <?php else: ?>
                                            <span class="notification-count"><?php echo $orderNotificationCount; ?></span>
                                        <?php endif; ?>
                                    </a>
                                    <ul class="marketplace-dropdown-menu">
                                    <span class="notify-point"></span>
                                    <?php
                                    $orderDisplayCount = 1; 
                                    foreach($block->getMarketplaceOrderCollection() as $order): 
                                        if($orderDisplayCount <= 5):
                                        ?>
                                        <li class="notifications-entry">
                                            <strong class="notifications-entry-title">
                                                <?php echo $block->getOrderNotificationTitle($order->getOrderId()); ?> 
                                            </strong>
                                            <p class="notifications-entry-description _cutted">
                                                <a href="<?php echo $block->getUrl('marketplace/order/view', ['id'=>$order->getOrderId(), 'n' => 1,'_secure' => $this->getRequest()->isSecure()])?>" class="notifications-entry-description-start">
                                                    <span>
                                                        <?php echo $block->getOrderNotificationDesc($order->getOrderId()); ?>                                                        
                                                    </span>
                                                </a>
                                            </p>
                                            <time class="notifications-entry-time">
                                                <?php echo $block->getOrderCreatedDate($order->getOrderId()); ?>
                                            </time>
                                        </li>
                                    <?php 
                                        $orderDisplayCount++;
                                        endif;
                                    endforeach; ?>
                                    <?php 
                                        if($orderDisplayCount > 5):
                                    ?>    
                                        <li class="notifications-entry notifications-entry-last">
                                            <a href="<?php echo $block->getUrl('marketplace/order/history', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                                <?php echo __('Click here to view order history'); ?>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    </ul>
                                </div>
                                <?php } ?>
                                <!-- Orders Notification End -->                      
                            <?php 
                            } ?> 
                        </li>
                    <?php }
                     ?>
                    <div id="marketplace-notification-component" data-bind="scope:'notification-content'">
                        <script type="text/x-magento-init">
                        {
                            "#marketplace-notification-component": {
                                "Magento_Ui/js/core/app":  <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
                            }
                        }
                        </script>
                        <?php echo $block->getChildHtml('reply_template'); ?>
                    </div>
                 <!--    <?php 
                 if(false){ ?>    
                    <?php echo $block->getChildHtml();?>
                    <li class="nav item <?php echo strpos($magentoCurrentUrl,'marketplace/account/becomepartner')? "current":"";?>">
                        <?php if(strpos($magentoCurrentUrl,'marketplace/account/becomeseller') !== false){ ?> 
                            <strong><?php echo __('Become Seller') ?></strong>    
                        <?php }         
                        else{ ?>    
                            <a href="<?php echo $block->getUrl('marketplace/account/becomeseller', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                <?php echo __('Become Seller') ?>
                            </a>                    
                        <?php } ?>      
                    </li>       
                <?php 
                } ?> -->
            </ul>
        </nav>
    </div>
</div>
<?php }
?>
<!-- echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('tredie-mobile-everyskip-menutop-right')->toHtml(); -->