<?php if ($block->isShow()): ?>
<div class="reports-report-block-switcher">
    <label for="store_switcher"><?php echo __('Show Report For:') ?></label>
    <select name="store_switcher" id="store_switcher" onchange="return switchStore(this);">
        <option value=""><?php echo __('All Websites') ?></option>
        <?php foreach ($block->getWebsiteCollection() as $_website): ?>
            <?php $showWebsite = false ?>
            <?php foreach ($block->getGroupCollection($_website) as $_group): ?>
                <?php $showGroup = false ?>
                <?php foreach ($block->getStoreCollection($_group) as $_store): ?>
                    <?php if ($showWebsite == false): ?>
                        <?php $showWebsite = true ?>
                        <option website="true" value="<?php echo implode(',', $_website->getStoreIds()) ?>"<?php if ($block->getRequest()->getParam('store_ids') == implode(',', $_website->getStoreIds())): ?> selected<?php endif ?>><?php echo $block->escapeHtml($_website->getName()) ?></option>
                    <?php endif ?>
                    <?php if ($showGroup == false): ?>
                        <?php $showGroup = true ?>
                        <option group="true" value="<?php echo implode(',', $_group->getStoreIds()) ?>"<?php if ($block->getRequest()->getParam('store_ids') == implode(',', $_group->getStoreIds())): ?> selected<?php endif ?>>&nbsp;&nbsp;&nbsp;<?php echo $block->escapeHtml($_group->getName()) ?></option>
                    <?php endif ?>
                    <option value="<?php echo $_store->getId() ?>"<?php if ($block->getStoreId() == $_store->getId()): ?> selected<?php endif ?>>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $block->escapeHtml($_store->getName()) ?></option>
                <?php endforeach ?>
                <?php if ($showGroup): ?>
                    </optgroup>
                <?php endif ?>
            <?php endforeach ?>
        <?php endforeach ?>
    </select>

    <script type="text/javascript">
        function switchStore(obj){
            var storeParam = obj.value ? 'store_ids/' + obj.value + '/' : '';
            if(obj.switchParams) {
                storeParam+= obj.switchParams;
            }
            setLocation('<?php echo $block->getSwitchUrl() ?>' + storeParam);
        }
    </script>
</div>
<?php endif ?>
